version: "3"
services:
  traefik:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "443:443"     # The HTTPS port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/${TRAEFIK_CONFIG:-traefik_dev.toml}:/traefik.toml
      - ./traefik/acme.json:/acme.json

  postgres:
    image: "postgres:9.6"
    volumes:
      - ./db-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: odk
      POSTGRES_PASSWORD: odk
      POSTGRES_DATABASE: odk

  mail:
    build:
      context: .
      dockerfile: mail.dockerfile
    environment:
      - MAILNAME=${DOMAIN}

  service:
    build:
      context: .
      dockerfile: service.dockerfile
    depends_on:
      - postgres
      - mail
    volumes:
      - ./data/transfer:/data/transfer
    environment:
      - DOMAIN=${DOMAIN}
    command: [ "./wait-for-it.sh", "postgres:5432", "--", "./start-odk.sh" ]

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    depends_on:
      - service
    # environment:
      # - SSL_TYPE=${SSL_TYPE}
      # - DOMAIN=${DOMAIN}
      # - CERTBOT_EMAIL=${SYSADMIN_EMAIL}
    ports:
      - 80
    labels:
      - "traefik.port=80"
      - "traefik.backend=front"
      - "traefik.frontend.rule=Host:${BASE_URL:-localhost}" # add another rule with ";Host:host"
      - "traefik.enable=true"